server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: xh_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_storage
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      senta: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
