server:
  port: 80
spring:
  application:
    name: cloud-consumer-hystrix-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000
feign:
  hystrix:
    enabled: true