server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: localhost://9411
    sleuth:
      sampler:
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
     # defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
    registry-fetch-interval-seconds: 15
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: payment8001
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities



