server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb:http://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/timeout/**   #断言,路径相匹配的进行路由
        - id: payment_routh2
          uri: lb:http://cloud-payment-service
          predicates:
            - Path=/payment/get/lb/**   #断言,路径相匹配的进行路由
            #- After=2020-09-10T09:27:26.384+08:00[Asia/Shanghai]
            #- Cookie=username,xh
            #- Before=2020-09-10T09:27:26.384+08:00[Asia/Shanghai]
            #- Between=2020-09-10T09:27:26.384+08:00[Asia/Shanghai],2020-09-10T10:50:26.384+08:00[Asia/Shanghai]
#            - Header=X-Request-Id,\d+
#            - Method=get
#            - Query=username,\d+
#        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#            uri: lb:http://cloud-payment-service   #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/get/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

