server:
  port: 80
spring:
  application:
    name: consul-order-service
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500



